name: Trigger auto deployment for ghtest

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ app21 ]
    paths:
    - '**'
    - '.github/workflows/ghtest-AutoDeployTrigger-b0131251-84a9-48d8-86de-307efb365e8c.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: ca5d1f8ea6ddacr.azurecr.io
          username: ${{ secrets.GHTEST_REGISTRY_USERNAME }}
          password: ${{ secrets.GHTEST_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ca5d1f8ea6ddacr.azurecr.io/ghtest:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.GHTEST_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n ghtest -g helloworldrg --server ca5d1f8ea6ddacr.azurecr.io --username  ${{ secrets.GHTEST_REGISTRY_USERNAME }} --password ${{ secrets.GHTEST_REGISTRY_PASSWORD }}
            az containerapp update -n ghtest -g helloworldrg --image ca5d1f8ea6ddacr.azurecr.io/ghtest:${{ github.sha }}
