name: Trigger auto deployment for containerapp ghtest4

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/ghtest4-AutoDeployTrigger-f0d305a1-9f2c-46e2-93b0-4547dd415fa7.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: sstrawn.azurecr.io
          username: ${{ secrets.GHTEST4_REGISTRY_USERNAME }}
          password: ${{ secrets.GHTEST4_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: sstrawn.azurecr.io/ghtest4:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.GHTEST4_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            echo "Installing containerapp extension"
            az config set extension.use_dynamic_install=yes_without_prompt
            echo "Starting Deploying"
            az containerapp registry set -n ghtest4 -g container_apps --server sstrawn.azurecr.io --username  ${{ secrets.GHTEST4_REGISTRY_USERNAME }} --password ${{ secrets.GHTEST4_REGISTRY_PASSWORD }}
            az containerapp update -n ghtest4 -g container_apps --image sstrawn.azurecr.io/ghtest4:${{ github.sha }}
