name: Trigger auto deployment for hftest

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ app21 ]
    paths:
    - '**'
    - '.github/workflows/hftest-AutoDeployTrigger-a65785dc-7075-4e8c-bcf0-dfe102accb4c.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: cacb315c7af9acr.azurecr.io
          username: ${{ secrets.HFTEST_REGISTRY_USERNAME }}
          password: ${{ secrets.HFTEST_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: cacb315c7af9acr.azurecr.io/hftest:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.HFTEST_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n hftest -g helloworld --server cacb315c7af9acr.azurecr.io --username  ${{ secrets.HFTEST_REGISTRY_USERNAME }} --password ${{ secrets.HFTEST_REGISTRY_PASSWORD }}
            az containerapp update -n hftest -g helloworld --image cacb315c7af9acr.azurecr.io/hftest:${{ github.sha }}
