name: Trigger auto deployment for containerapp newgh1

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ app1 ]
    paths:
    - '**'
    - '.github/workflows/newgh1-AutoDeployTrigger-75e111e7-a221-46a3-be5a-a4dd607a200d.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: cauapa9e5460acr.azurecr.io
          username: ${{ secrets.NEWGH1_REGISTRY_USERNAME }}
          password: ${{ secrets.NEWGH1_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: cauapa9e5460acr.azurecr.io/newgh1:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.NEWGH1_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            echo "Installing containerapp extension"
            az config set extension.use_dynamic_install=yes_without_prompt
            echo "Starting Deploying"
            az containerapp registry set -n newgh1 -g sca --server cauapa9e5460acr.azurecr.io --username  ${{ secrets.NEWGH1_REGISTRY_USERNAME }} --password ${{ secrets.NEWGH1_REGISTRY_PASSWORD }}
            az containerapp update -n newgh1 -g sca --image cauapa9e5460acr.azurecr.io/newgh1:${{ github.sha }}
