name: Trigger auto deployment for containerapp newgh32

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ app3 ]
    paths:
    - '**'
    - '.github/workflows/newgh32-AutoDeployTrigger-b2642062-2219-4328-8595-a6e74dbb7fe9.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: cauapa9e5460acr.azurecr.io
          username: ${{ secrets.NEWGH32_REGISTRY_USERNAME }}
          password: ${{ secrets.NEWGH32_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: cauapa9e5460acr.azurecr.io/newgh32:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.NEWGH32_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            echo "Installing containerapp extension"
            az config set extension.use_dynamic_install=yes_without_prompt
            echo "Starting Deploying"
            az containerapp registry set -n newgh32 -g sca --server cauapa9e5460acr.azurecr.io --username  ${{ secrets.NEWGH32_REGISTRY_USERNAME }} --password ${{ secrets.NEWGH32_REGISTRY_PASSWORD }}
            az containerapp update -n newgh32 -g sca --image cauapa9e5460acr.azurecr.io/newgh32:${{ github.sha }}
