name: Trigger auto deployment for containerapp newgh6

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ app6 ]
    paths:
    - '**'
    - '.github/workflows/newgh6-AutoDeployTrigger-ea8fd581-6346-44e0-9880-b8761a2fd541.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: caeastus2envacr.azurecr.io
          username: ${{ secrets.NEWGH6_REGISTRY_USERNAME }}
          password: ${{ secrets.NEWGH6_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: caeastus2envacr.azurecr.io/newgh6:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.NEWGH6_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            echo "Installing containerapp extension"
            az config set extension.use_dynamic_install=yes_without_prompt
            echo "Starting Deploying"
            az containerapp registry set -n newgh6 -g silasstrawn_rg_7348 --server caeastus2envacr.azurecr.io --username  ${{ secrets.NEWGH6_REGISTRY_USERNAME }} --password ${{ secrets.NEWGH6_REGISTRY_PASSWORD }}
            az containerapp update -n newgh6 -g silasstrawn_rg_7348 --image caeastus2envacr.azurecr.io/newgh6:${{ github.sha }}
