name: Trigger auto deployment for containerapp newgh13-1

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ app13 ]
    paths:
    - '**'
    - '.github/workflows/newgh13-1-AutoDeployTrigger-a5c0100c-0be7-41c2-97ea-f2f89d8438bc.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: cacae407bdccacr.azurecr.io
          username: ${{ secrets.NEWGH131_REGISTRY_USERNAME }}
          password: ${{ secrets.NEWGH131_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: cacae407bdccacr.azurecr.io/newgh13-1:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.NEWGH131_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            echo "Installing containerapp extension"
            az config set extension.use_dynamic_install=yes_without_prompt
            echo "Starting Deploying"
            az containerapp registry set -n newgh13-1 -g container_apps --server cacae407bdccacr.azurecr.io --username  ${{ secrets.NEWGH131_REGISTRY_USERNAME }} --password ${{ secrets.NEWGH131_REGISTRY_PASSWORD }}
            az containerapp update -n newgh13-1 -g container_apps --image cacae407bdccacr.azurecr.io/newgh13-1:${{ github.sha }}
