name: Trigger auto deployment for containerapp newgh20

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ app20 ]
    paths:
    - '**'
    - '.github/workflows/newgh20-AutoDeployTrigger-b29b0e06-bd11-4fe4-91c3-b2a3441d1148.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: ca9bdb5876bcacr.azurecr.io
          username: ${{ secrets.NEWGH20_REGISTRY_USERNAME }}
          password: ${{ secrets.NEWGH20_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ca9bdb5876bcacr.azurecr.io/newgh20:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.NEWGH20_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            echo "Installing containerapp extension"
            az config set extension.use_dynamic_install=yes_without_prompt
            echo "Starting Deploying"
            az containerapp registry set -n newgh20 -g container_apps --server ca9bdb5876bcacr.azurecr.io --username  ${{ secrets.NEWGH20_REGISTRY_USERNAME }} --password ${{ secrets.NEWGH20_REGISTRY_PASSWORD }}
            az containerapp update -n newgh20 -g container_apps --image ca9bdb5876bcacr.azurecr.io/newgh20:${{ github.sha }}
