name: Trigger auto deployment for containerapp newgh21

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ app21 ]
    paths:
    - '**'
    - '.github/workflows/newgh21-AutoDeployTrigger-252b78b8-fb96-418f-bc07-62d271f142de.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: sstrawn.azurecr.io
          username: ${{ secrets.NEWGH21_REGISTRY_USERNAME }}
          password: ${{ secrets.NEWGH21_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: sstrawn.azurecr.io/newgh21:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.NEWGH21_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            echo "Installing containerapp extension"
            az config set extension.use_dynamic_install=yes_without_prompt
            echo "Starting Deploying"
            az containerapp registry set -n newgh21 -g container_apps --server sstrawn.azurecr.io --username  ${{ secrets.NEWGH21_REGISTRY_USERNAME }} --password ${{ secrets.NEWGH21_REGISTRY_PASSWORD }}
            az containerapp update -n newgh21 -g container_apps --image sstrawn.azurecr.io/newgh21:${{ github.sha }}
