name: Trigger auto deployment for containerapp newgh9

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ app8 ]
    paths:
    - '**'
    - '.github/workflows/newgh9-AutoDeployTrigger-47b20bea-1e39-452b-945d-1020d1a30bcf.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: ca14b59080fcacr.azurecr.io
          username: ${{ secrets.NEWGH9_REGISTRY_USERNAME }}
          password: ${{ secrets.NEWGH9_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ca14b59080fcacr.azurecr.io/newgh9:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.NEWGH9_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            echo "Installing containerapp extension"
            az config set extension.use_dynamic_install=yes_without_prompt
            echo "Starting Deploying"
            az containerapp registry set -n newgh9 -g silasstrawn_rg_1695 --server ca14b59080fcacr.azurecr.io --username  ${{ secrets.NEWGH9_REGISTRY_USERNAME }} --password ${{ secrets.NEWGH9_REGISTRY_PASSWORD }}
            az containerapp update -n newgh9 -g silasstrawn_rg_1695 --image ca14b59080fcacr.azurecr.io/newgh9:${{ github.sha }}
