name: Trigger auto deployment for containerapp newnewgh14

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ app14 ]
    paths:
    - '**'
    - '.github/workflows/newnewgh14-AutoDeployTrigger-5ee2201a-d532-4a20-82fa-4a1b00185fd6.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: cacae407bdccacr.azurecr.io
          username: ${{ secrets.NEWNEWGH14_REGISTRY_USERNAME }}
          password: ${{ secrets.NEWNEWGH14_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: cacae407bdccacr.azurecr.io/newnewgh14:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.NEWNEWGH14_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            echo "Installing containerapp extension"
            az config set extension.use_dynamic_install=yes_without_prompt
            echo "Starting Deploying"
            az containerapp registry set -n newnewgh14 -g container_apps --server cacae407bdccacr.azurecr.io --username  ${{ secrets.NEWNEWGH14_REGISTRY_USERNAME }} --password ${{ secrets.NEWNEWGH14_REGISTRY_PASSWORD }}
            az containerapp update -n newnewgh14 -g container_apps --image cacae407bdccacr.azurecr.io/newnewgh14:${{ github.sha }}
