name: Trigger auto deployment for uptest

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ app21 ]
    paths:
    - '**'
    - '.github/workflows/uptest-AutoDeployTrigger-0b7c7638-46f1-4389-9b20-08d502f860a4.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: caabd688af59acr.azurecr.io
          username: ${{ secrets.UPTEST_REGISTRY_USERNAME }}
          password: ${{ secrets.UPTEST_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: caabd688af59acr.azurecr.io/uptest:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.UPTEST_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n uptest -g helloworld --server caabd688af59acr.azurecr.io --username  ${{ secrets.UPTEST_REGISTRY_USERNAME }} --password ${{ secrets.UPTEST_REGISTRY_PASSWORD }}
            az containerapp update -n uptest -g helloworld --image caabd688af59acr.azurecr.io/uptest:${{ github.sha }}
